services:
  frontend:
    build:
      context: https://gitlab.com/Ernela/neomovies-web.git
      dockerfile: Dockerfile
    container_name: neomovies-frontend
    ports:
      - "4173:4173"
    restart: unless-stopped

  backend:
    build:
      context: https://gitlab.com/Ernela/neomovies-api.git
      dockerfile: Dockerfile
    container_name: neomovies-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://db:27017/neomovies
      - BASE_URL=http://localhost:3000
      - FRONTEND_URL=http://localhost:4173
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: neomovies-database
    ports:
      - "27017:27017"
    volumes:
      - ./neomovies-database:/data/db
    restart: unless-stopped
